# Generated by Django 3.2.8 on 2021-11-12 02:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('login_ip', models.CharField(max_length=50)),
                ('action_info', models.CharField(max_length=50)),
                ('action_path', models.CharField(max_length=50)),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('operating_level', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SysActionLog',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='父菜单ID，一级菜单为0')),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='菜单URL')),
                ('perms', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权(多个用逗号分隔，如：user:list,user:create)')),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, verbose_name='类型 0：目录  1：菜单  2：按钮')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('orderNum', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('statu', models.IntegerField(verbose_name='代码为状态,单词少写了个s')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('statu', models.IntegerField(verbose_name='代码为状态，单词少写了个s')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_id', models.BigIntegerField()),
                ('menu_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('fullName', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('statu', models.IntegerField(verbose_name='代码为状态，单词少写了个s')),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('userId', models.IntegerField(verbose_name='用户的id')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sys_user_role',
            },
        ),
    ]
