# Generated by Django 3.2.8 on 2021-11-12 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
